- alias: 'Dispara Alarme Quando Armado e Ausente'
  trigger:
    - platform: state
      entity_id: binary_sensor.porta_cozinha
      to: 'on'
    - platform: state
      entity_id: binary_sensor.porta_sala
      to: 'on'
    - platform: state
      entity_id: binary_sensor.porta_varanda
      to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_away
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: armed_home
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.home_alarm




- alias: 'Alarme em PENDENTE'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'pending'
  action:
    - service: notify.notify
      data:
        message: "ALARM! O alarme está em PENDENTE"
    - service: media_player.volume_set
      data_template:
          entity_id: media_player.office_speaker2,media_player.kitchen_speaker
          volume_level: 0.6
    - service: tts.google_say
      entity_id: media_player.office_speaker2,media_player.kitchen_speaker
      data_template:
          message: '{{ ["O Alarme foi acionado. Você tem 20 segundos.", 
                        "O Alarme foi acionado. Você tem 20 segundos."] | random }}'
          language: 'pt-br'


- alias: 'Envia Notificação Quando Alarme Disparado'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'triggered'
  action:
    - service: notify.notify
      data:
        message: "ALARM! O alarme foi DISPARADO"




- alias: 'Envia Notificaçao quando Alarme é Desarmado'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'disarmed'
  action:
    - service: notify.notify
      data:
        message: "ALARM! O alarme foi desarmado em {{ states('sensor.date_time') }}"
    - service: media_player.volume_set
      data_template:
          entity_id: media_player.office_speaker2,media_player.kitchen_speaker
          volume_level: 0.5
    - service: tts.google_say
      entity_id: media_player.office_speaker2
      data_template:
          message: '{{ ["O Alarme foi desativado.", 
                        "O Alarme está desligado."] | random }}'
          language: 'pt-br'



- alias: 'Send notification when alarm is Armed in Away mode'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'armed_away'
  action:
    - service: notify.notify
      data:
        message: "ALARM! O alarme foi armado como Away em {{ states('sensor.date_time') }}"
    - service: media_player.volume_set
      data_template:
          entity_id: media_player.office_speaker2,media_player.kitchen_speaker
          volume_level: 0.5
    - service: tts.google_say
      entity_id: media_player.office_speaker2
      data_template:
          message: '{{ ["Alarme Ativado no modo 1.", 
                        "Alarme Ativado no modo Casa Vazia."] | random }}'
          language: 'pt-br'

- alias: 'Send notification when alarm is Armed in Home mode'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'armed_home'
  action:
    - service: notify.notify
      data:
        message: "ALARM! O alame foi armado como Home em {{ states('sensor.date_time') }}"
    - service: media_player.volume_set
      data_template:
          entity_id: media_player.office_speaker2,media_player.kitchen_speaker
          volume_level: 0.5
    - service: tts.google_say
      entity_id: media_player.office_speaker2
      data_template:
          message: '{{ ["Alarme Ativado no modo 2.", 
                        "Alarme Ativado no modo Casa Cheia."] | random }}'
          language: 'pt-br'